name: calender_application
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  import_sorter: ^4.6.0
  very_good_analysis: ^5.1.0
  flutter_datetime_picker_plus: ^2.1.0
  flutter_riverpod: ^2.4.10
  drift: ^1.5.0
  path: ^1.8.3
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.20
  drift_dev: ^1.7.1
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  freezed: ^2.2.0
  hooks_riverpod: ^2.4.10
  flutter_localization: ^0.2.0
  flutter_hooks: ^0.20.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
flutter:
  uses-material-design: true